### ISSUE TITLE
Getting user email

### ISSUE THREAD

**Issue by dmisiuk** [vkolodrevskiy/spring-social-vkontakte#19]

**Comment by SergiiShapoval** [comment]
Still can't access to user email, even when user allows it

**Comment by SergiiShapoval** [comment]
Is it a solution - https://github.com/PGoski/spring-social-vkontakte/commit/c59099bd8e98c6a5ef64e696d98f1bfe9288581f

**Comment by RomanSyroeshko** [comment]
Anybody succeeded with that?

**Comment by RomanSyroeshko** [comment]
[Latest](https://github.com/vkolodrevskiy/spring-social-vkontakte/pull/27) discussion upon the problem.

**Comment by vkolodrevskiy** [comment]
spring-social-vkontakte was refactored in 2.0.0 and now is using VK Java SDK to interact with VK API instead of own API client implementation. Sample of getting email you can check under https://github.com/vkolodrevskiy/spring-social-samples/blob/master/spring-social-showcase/src/main/java/org/springframework/social/showcase/vkontakte/VKontakteProfileController.java

**Comment by RomanSyroeshko** [comment]
Awesome! 👍  @vkolodrevskiy, will the version be available at `maven.org`?

**Comment by vkolodrevskiy** [comment]
@RomanSyroeshko it's available in own repo. See details https://github.com/vkolodrevskiy/spring-social-vkontakte/wiki/Distribution

**Comment by RomanSyroeshko** [comment]
Any chances to have the changes in stable release? Currently spring-social-vkontakte uses snapshot versions of Spring and Spring Social. I can't afford using them in production. Maybe you could switch back to GA versions of the dependencies?

Thanks.
